### ISSUE TITLE
AppVeyor CI "Not a git repository" error

### ISSUE THREAD

**Issue by chrisblossom** [codecov/codecov-node#100]
I'm getting the error below when running Codecov on AppVeyor. Works as expected on CircleCI. Please advise.

https://github.com/chrisblossom/testing-codecov
https://ci.appveyor.com/project/chrisblossom/testing-codecov

```
Ran all test suites.
_____ _
/ ____| | |
| | ___ __| | ___ ___ _____ __
| | / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| | __/ (_| (_) \ V /
\_____\___/ \__,_|\___|\___\___/ \_/
v3.0.2
==> Detecting CI Provider
AppVeyor CI Detected
==> Configuration:
Endpoint: https://codecov.io
{ commit: 'a0f9cbd7f41a8457943d6b8a8a4d04e46ccbf98c',
branch: 'master',
package: 'node-v3.0.2' }
==> Building file structure
fatal: Not a git repository (or any of the parent directories): .git
abort: no repository found in 'C:\projects\testing-codecov' (.hg not found)!
child_process.js:516
throw err;
^
Error: Command failed: git ls-files || hg locate
fatal: Not a git repository (or any of the parent directories): .git
abort: no repository found in 'C:\projects\testing-codecov' (.hg not found)!
at checkExecSyncError (child_process.js:473:13)
at execSync (child_process.js:513:13)
at Object.upload (C:\projects\testing-codecov\node_modules\codecov\lib\codecov.js:291:13)
at Object.<anonymous> (C:\projects\testing-codecov\node_modules\codecov\bin\codecov:26:9)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.runMain (module.js:611:10)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test.ci"
```

**Comment by eddiemoore** [comment]
Hi @chrisblossom can you update to v3.0.2 and see if that has fixed the issue

**Comment by chrisblossom** [comment]
It works! Looks like #75 fixed the issue. Thank you!

**Comment by eddiemoore** [comment]
:+1: good to hear
