### ISSUE TITLE
3.8.0 is a breaking change for those using older node versions

### ISSUE THREAD

**Issue by kaymo** [codecov/codecov-node#237]
Codecov release 3.8.0 includes upgrading  to `teeny-request@7.0.0`: https://github.com/codecov/codecov-node/pull/225/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR19

`teeny-request@7.0.0+` now requires `node@10+`: https://github.com/googleapis/teeny-request/blob/v7.0.0/package.json#L7-L9

=> `codecov@3.8.0` is a breaking change for those on older node versions, despite still listing `node@4+`: https://github.com/codecov/codecov-node/blob/master/package.json#L24-L26

Example build error: 
```
[15:11:27][Report test coverage]         ...(reqOpts.timeout && { timeout: reqOpts.timeout }),
[15:11:27][Report test coverage]         ^^^
[15:11:27][Report test coverage] 
[15:11:27][Report test coverage] SyntaxError: Unexpected token ...
[15:11:27][Report test coverage]     at exports.runInThisContext (vm.js:53:16)
[15:11:27][Report test coverage]     at Module._compile (module.js:387:25)
[15:11:27][Report test coverage]     at Object.Module._extensions..js (module.js:422:10)
[15:11:27][Report test coverage]     at Module.load (module.js:357:32)
[15:11:27][Report test coverage]     at Function.Module._load (module.js:314:12)
[15:11:27][Report test coverage]     at Module.require (module.js:367:17)
[15:11:27][Report test coverage]     at require (internal/module.js:20:19)
[15:11:27][Report test coverage]     at Object.<anonymous> (Z:\.npm-cache\77277d7c\node_modules\codecov\lib\codecov.js:3:15)
[15:11:27][Report test coverage]     at Module._compile (module.js:413:34)
[15:11:27][Report test coverage]     at Object.Module._extensions..js (module.js:422:10)
[15:11:27][Report test coverage] 
[15:11:27][Report test coverage] npm ERR! Windows_NT 6.3.9600
[15:11:27][Report test coverage] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:report-coverage"
[15:11:27][Report test coverage] npm ERR! node v5.12.0
[15:11:27][Report test coverage] npm ERR! npm  v3.10.9
[15:11:27][Report test coverage] npm ERR! code ELIFECYCLE
```

**Comment by thomasrockhu** [comment]
@kaymo, I'll look to release 3.8.1 to address this week, thanks for bringing it up. We will likely, however, be removing support for `node@8` and earlier in subsequent releases.
