### ISSUE TITLE
Spaces in directory names aren't supported

### ISSUE THREAD

**Issue by probablyup** [codecov/codecov-node#41]
```
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v1.0.1
==> Detecting CI Provider
    Jenkins CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ service: 'jenkins',
  commit: '862ef1adb798c3ee619bed7e04f4e14fe272f539',
  branch: 'origin/pr/534/head',
  build: '2497',
  build_url: 'http://jenkins.lion.enigma/job/LION%20-%20PR%20-%201%20-%20UNIT/2497/',
  root: '/var/lib/jenkins/workspace/LION - PR - 1 - UNIT',
  pr: undefined,
  token: '****',
  package: 'node-v1.0.1' }
==> Building file structure
/bin/sh: 1: cd: can't cd to /var/lib/jenkins/workspace/LION
/bin/sh: 1: hg: not found
child_process.js:526
    throw err;
    ^

Error: Command failed: cd /var/lib/jenkins/workspace/LION - PR - 1 - UNIT && git ls-files || hg locate
/bin/sh: 1: cd: can't cd to /var/lib/jenkins/workspace/LION
/bin/sh: 1: hg: not found

    at checkExecSyncError (child_process.js:483:13)
    at execSync (child_process.js:523:13)
    at Object.upload (/var/lib/jenkins/workspace/LION - PR - 1 - UNIT/node_modules/codecov/lib/codecov.js:215:13)
    at Object.<anonymous> (/var/lib/jenkins/workspace/LION - PR - 1 - UNIT/node_modules/codecov/bin/codecov:24:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Build step 'Execute shell' marked build as failure
```

**Comment by ypconstante** [comment]
The solution for me when working with jenkins is to use this command when calling codecov
`codecov --root="$(echo $WORKSPACE | sed 's/\s/\\ /')"`

**Comment by stevepeak** [comment]
@eddiemoore does #85 resolve this issue too?

**Comment by thomasrockhu** [comment]
Closing this out due to age. Feel free to re-open if this is still an issue.
