### ISSUE TITLE
Coverage report upload failing on appveyor with v2.2.0

### ISSUE THREAD

**Issue by reeteshranjan** [codecov/codecov-node#61]
Here is the command ran:

```
.\node_modules\.bin\istanbul cover .\node_modules\mocha\bin\_mocha  -- --reporter lcovonly --ui bdd -R spec -t 5000 tests\unit
```

The output:

```
=============================================================================
Writing coverage object [C:\projects\cross-browser-tests-runner\coverage\coverage.json]
Writing coverage reports at [C:\projects\cross-browser-tests-runner\coverage]
=============================================================================
=============================== Coverage summary ===============================
Statements   : 99.21% ( 501/505 )
Branches     : 89.83% ( 159/177 )
Functions    : 99.15% ( 116/117 )
Lines        : 99.21% ( 500/504 )
================================================================================
.\node_modules\.bin\codecov
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v2.2.0
==> Detecting CI Provider
    AppVeyor CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ service: 'appveyor',
  commit: '9f8c9ac60e2e08491d5a6a533335bbfebb76cf1b',
  branch: 'master',
  pr: undefined,
  job: 'reeteshranjan/cross-browser-tests-runner/1.0.47',
  build: '8dkkhy310n3fteu4',
  slug: 'reeteshranjan/cross-browser-tests-runner',
  token: '6ddf3961-0a50-4816-bf4c-e0cfb5f3a922',
  package: 'node-v2.2.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
File not found - '*.gcno'
    Failed to run gcov command.
==> Scanning for reports
FIND: Parameter format not correct
child_process.js:524
    throw err;
    ^
Error: Command failed: find . -type f \( -name '*coverage.*' -or -name 'nosetests.xml' -or -name 'jacoco*.xml' -or -name 'clover.xml' -or -name 'report.xml' -or -name 'cobertura.xml' -or -name 'luacov.report.out' -or -name 'lcov.info' -or -name '*.lcov' -or -name 'gcov.info' -or -name '*.gcov' -or -name '*.lst' \) -not -name '*.sh' -not -name '*.data' -not -name '*.py' -not -name '*.class' -not -name '*.xcconfig' -not -name 'Coverage.profdata' -not -name 'phpunit-code-coverage.xml' -not -name 'coverage.serialized' -not -name '*.pyc' -not -name '*.cfg' -not -name '*.egg' -not -name '*.whl' -not -name '*.html' -not -name '*.js' -not -name '*.cpp' -not -name 'coverage.jade' -not -name 'include.lst' -not -name 'inputFiles.lst' -not -name 'createdFiles.lst' -not -name 'coverage.html' -not -name 'scoverage.measurements.*' -not -name 'test_*_coverage.txt' -not -path '*/vendor/*' -not -path '*/htmlcov/*' -not -path '*/home/cainus/*' -not -path '*/virtualenv/*' -not -path '*/js/generated/coverage/*' -not -path '*/.virtualenv/*' -not -path '*/virtualenvs/*' -not -path '*/.virtualenvs/*' -not -path '*/.env/*' -not -path '*/.envs/*' -not -path '*/env/*' -not -path '*/envs/*' -not -path '*/.venv/*' -not -path '*/.venvs/*' -not -path '*/venv/*' -not -path '*/venvs/*' -not -path '*/.git/*' -not -path '*/.hg/*' -not -path '*/.tox/*' -not -path '*/__pycache__/*' -not -path '*/.egg-info*' -not -path '*/$bower_components/*' -not -path '*/node_modules/*' -not -path '*/conftest_*.c.gcov'
FIND: Parameter format not correct
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at Object.upload (C:\projects\cross-browser-tests-runner\node_modules\codecov\lib\codecov.js:264:18)
    at Object.<anonymous> (C:\projects\cross-browser-tests-runner\node_modules\codecov\bin\codecov:26:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
Command exited with code 1
```

What am I doing wrong here?

Linux build on circlci and OSX build on travis have been working fine for last one week or so across several builds already created.

The appveyor build url: https://ci.appveyor.com/project/reeteshranjan/cross-browser-tests-runner/build/1.0.47

appveyor.yml url: https://github.com/reeteshranjan/cross-browser-tests-runner/blob/master/appveyor.yml

**Comment by eddiemoore** [comment]
@reeteshranjan yea this is a known issue. Looking into supporting the node scripts on windows. At this moment the node codecov CLI only supports *nix systems.

**Comment by reeteshranjan** [comment]
Oh, I read somewhere that appveyor is a supported ci environment, and assumed that must mean Windows works. Is there any ETA on the Windows support?

**Comment by eddiemoore** [comment]
You can have a look into the bash script. @stevepeak should be able to point you in the right direction. But at the moment there are issues with the node script for windows. No timeline at the moment. But hopefully soon.

**Comment by reeteshranjan** [comment]
@eddiemoore @stevepeak I have created https://github.com/codecov/codecov-node/pull/62 with all changes required for coverage upload to work on Windows. The pull requested has details of all the verification done. A sample project with a working Appveyor build and codecov.io reports project was used to verify the changes, and all these details are available in the pull request.
