### ISSUE TITLE
Not compatible on node 0.12 because of `request`

### ISSUE THREAD

**Issue by aoberoi** [codecov/codecov-node#72]
I'm getting issues uploading coverage data from node 0.12 because the package depends on a version of `request` that isn't compatible with that engine. here is the error:

```
$ npm run codecov
> hubot-slack@4.4.0 codecov /home/travis/build/slackapi/hubot-slack
> codecov
/home/travis/build/slackapi/hubot-slack/node_modules/codecov/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/slackapi/hubot-slack/node_modules/codecov/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by aoberoi** [comment]
the fix would be to pin the version of request to 2.77.0. Contrary to what it #67 claims, [the vulnerability](https://snyk.io/vuln/npm:request:20160119) isn't present on versions 2.68.0 or greater.
