### ISSUE TITLE
fatal: Not a git repository

### ISSUE THREAD

**Issue by BeauBouchard** [codecov/codecov-node#89]
I am getting an error from the current version of this in one of the repos we are using it in. 

```

 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v3.0.0
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
fatal: Not a git repository (or any of the parent directories): .git
/bin/sh: hg: not found
child_process.js:635
    throw err;
    ^
Error: Command failed: git rev-parse --abbrev-ref HEAD || hg branch
fatal: Not a git repository (or any of the parent directories): .git
/bin/sh: hg: not found
    at checkExecSyncError (child_process.js:592:13)
    at execSync (child_process.js:632:13)
    at Object.branch ([redacted]/node_modules/codecov/lib/git.js:6:12)
    at Object.configuration ([redacted]/node_modules/codecov/lib/services/localGit.js:7:22)
    at detectProvider ([redacted]/node_modules/codecov/lib/detect.js:25:20)
    at Object.upload ([redacted]/node_modules/codecov/lib/codecov.js:229:13)
    at Object.<anonymous> ([redacted]/node_modules/codecov/bin/codecov:26:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```
I am not sure if it is related to #1 or not. This happens on travis-ci run for a private repo. 
Its inside a docker container
`node v8.9.4 (npm v5.6.0)`
`Docker version 17.06.0-ce, build 02c1d87`

**Comment by rogoman** [comment]
I'm experiencing the same issue.

**Comment by ajkamel** [comment]
Based on testing on my production environment it looks like if you use Node 9 + (eg. mhart/alpine-node:9.11.1)  it does not have git installed which might throw this error.

**Comment by BeauBouchard** [comment]
I believe it was what @ajkamel described in my original scenario, sorry for not following up on this earlier.

**Comment by eddiemoore** [comment]
Issue seems fixed now

**Comment by peiny** [comment]
Need to install git in docker like using "apt add git"

**Comment by DzmitryU** [comment]
> Need to install git in docker like using "apt add git"

Also you need to copy or mount .git folder into your container
